development:
 adapter: postgresql
   encoding: utf8
  reconnect: false
  database: flatman_develop
  pool: 5
  username: flatman_develop
  password: "schnitzel"

test:
   adapter: postgresql
  encoding: utf8
  reconnect: false
  database: flatman_test
  pool: 5
  username: flatman_test
  password: "schnitzel"
  host: localhost

production:
   adapter: postgresql
  encoding: utf8
  reconnect: false
  database: flatman_production
  pool: 5
  username: flatman_production
  password: "schnitzel"
  host: localhost
